- hosts: localhost
  connection: local
  vars_files:
    - ./src_vars.yml

  tasks:
    - name: Generalize WEB VM
      azure_rm_virtualmachine:
        resource_group: "{{ src_rg_name }}"
        name: "{{ src_web_vm_name }}"
        generalized: yes

    - name: Generalize WAS VM
      azure_rm_virtualmachine:
        resource_group: "{{ src_rg_name }}"
        name: "{{ src_was_vm_name }}"
        generalized: yes

    - name: Create custom image for WEB VM
      azure_rm_image:
        resource_group: "{{ src_rg_name }}"
        name: "{{ src_web_vm_img_name }}"
        source: "{{ src_web_vm_name }}"
        
    - name: Create custom image for WAS VM
      azure_rm_image:
        resource_group: "{{ src_rg_name }}"
        name: "{{ src_was_vm_img_name }}"
        source: "{{ src_was_vm_name }}"
        