- hosts: localhost
  connection: local
  vars_files:
    - ./src_vars.yml

  tasks:
    - name: Create shared image gallery
      azure_rm_gallery:
        resource_group: "{{ src_rg_name }}"
        name: "{{ src_shared_gallery_name }}"
        location: "{{ location }}"
        description: This is the gallery description.