---
- name: Create source resource group if doesn't exist
  azure_rm_resourcegroup:
    name: "{{ src_rg_name }}"
    location: "{{ location }}"

- name: Create source virtual network
  azure_rm_virtualnetwork:
    resource_group: "{{ src_rg_name }}"
    name: "{{ src_vnet_name }}"
    address_prefixes: "{{ src_vnet_cidr }}"
    
- name: Add source subnet
  azure_rm_subnet:
    resource_group: "{{ src_rg_name }}"
    name: "{{ src_subnet_name }}"
    address_prefix: "{{ src_subnet_cidr }}"
    virtual_network: "{{ src_vnet_name }}"

- name: Create Public IP for source WEB
  azure_rm_publicipaddress:
    resource_group: "{{ src_rg_name }}"
    allocation_method: Static
    name: "{{ src_web_public_ip_name }}"

- name: Create Public IP for source WAS
  azure_rm_publicipaddress:
    resource_group: "{{ src_rg_name }}"
    allocation_method: Static
    name: "{{ src_was_public_ip_name }}"

- name: Create NSG that allows SSH and HTTP
  azure_rm_securitygroup: 
    resource_group: '{{ src_rg_name }}'
    name: '{{ src_nsg_name }}'
    rules: 
      - name: SSH 
        protocol: Tcp 
        destination_port_range: 22  
        access: Allow  
        priority: 100 
        direction: Inbound
      - name: WEB
        protocol: Tcp 
        destination_port_range: 80  
        access: Allow  
        priority: 101 
        direction: Inbound
      - name: WAS
        protocol: Tcp 
        destination_port_range: 8080  
        access: Allow  
        priority: 102
        direction: Inbound

- name: Create virtual network inteface cards for source WEB
  azure_rm_networkinterface:
    resource_group: "{{ src_rg_name }}"
    name: "{{ src_web_nic_name }}"
    virtual_network: "{{ src_vnet_name }}"
    subnet: "{{ src_subnet_name }}"
    security_group: '{{ src_nsg_name }}'
    ip_configurations:
      - name: default
        public_ip_address_name: "{{ src_web_public_ip_name }}"
        primary: True
        
- name: Create virtual network inteface cards for source WAS
  azure_rm_networkinterface:
    resource_group: "{{ src_rg_name }}"
    name: "{{ src_was_nic_name }}"
    virtual_network: "{{ src_vnet_name }}"
    subnet: "{{ src_subnet_name }}"
    security_group: '{{ src_nsg_name }}'
    ip_configurations:
      - name: default
        public_ip_address_name: "{{ src_was_public_ip_name }}"
        primary: True

- name: Create source WEB VM
  azure_rm_virtualmachine:
    resource_group: "{{ src_rg_name }}"
    name: "{{ src_web_vm_name }}"
    admin_username: "{{ admin_username }}"
    ssh_password_enabled: false
    ssh_public_keys:
      - path: /home/{{ admin_username }}/.ssh/authorized_keys
        key_data: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDRJ/xkWigsnIfDlWNUN5zCUUu4im203n+uvzoKfNcddaZbJRE1uEQCCNP5Vgxrj5jnVRukpp2jfSjeWdOolUNRHcvdLGjhZcCsRYdkQlEK4ObIjH/EDsquLXso+s5pOOxNIY6pHydQf3D8PKZuGkdv5WGmU/CqkRTKHYUJSr1+eg5LgHJKlkFZi98LXr+9FQjeqlEsplbCs6OhlGPo49tQld538q8b6FygUqXifneXbPlVVwB8tx/WZoC33pQKaSNooxDiRj55FORoXl4FfEtI0AWxNRVeQmYEBPBi58uEpiFg33pANlmeHoJWW6oMjcgeGqrKC9HZo+HyFmRsYYGQoWPJ8Q4pmg0T1qa3ooB7MKaXH+0BsLRQd587GNbVsLno+EY9hAGgCVUI9tcUUnVS6YWqsvm1CCYkx087UeECqvfuMBt5rwzCLXIZA8+zsRjvvpJ99bIqjXlZnEilC4FX+kgws2AoYA1fheRDbPjSFwn25W5pibUBAVSGgUOxYMPh4XYeNeQC6w25fWrQN7moP2xksn+eauRiZTUQ7fFbgCDYzIIV4y1EmtnzOGmsD8EP7EpVWr6W8EBOYbsMuusRhn0SyPFVMhqZ0tx39NyDs93/82MHGbgZxGf8jyBscwG40dOuyUeW8L8BZGRFU/Cl3rlyf94HeEoaaEa2wkaouw== azureuser@ansible-control"
    vm_size: Standard_B1ms
    network_interfaces: "{{ src_web_nic_name }}"
    image:
      offer: CentOS
      publisher: OpenLogic
      sku: '7.5'
      version: latest
    tags:
      level: dev
      application: web
      image: srcimg

- name: Create source WAS VM
  azure_rm_virtualmachine:
    resource_group: "{{ src_rg_name }}"
    name: "{{ src_was_vm_name }}"
    admin_username: "{{ admin_username }}"
    ssh_password_enabled: false
    ssh_public_keys:
      - path: /home/{{ admin_username }}/.ssh/authorized_keys
        key_data: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDRJ/xkWigsnIfDlWNUN5zCUUu4im203n+uvzoKfNcddaZbJRE1uEQCCNP5Vgxrj5jnVRukpp2jfSjeWdOolUNRHcvdLGjhZcCsRYdkQlEK4ObIjH/EDsquLXso+s5pOOxNIY6pHydQf3D8PKZuGkdv5WGmU/CqkRTKHYUJSr1+eg5LgHJKlkFZi98LXr+9FQjeqlEsplbCs6OhlGPo49tQld538q8b6FygUqXifneXbPlVVwB8tx/WZoC33pQKaSNooxDiRj55FORoXl4FfEtI0AWxNRVeQmYEBPBi58uEpiFg33pANlmeHoJWW6oMjcgeGqrKC9HZo+HyFmRsYYGQoWPJ8Q4pmg0T1qa3ooB7MKaXH+0BsLRQd587GNbVsLno+EY9hAGgCVUI9tcUUnVS6YWqsvm1CCYkx087UeECqvfuMBt5rwzCLXIZA8+zsRjvvpJ99bIqjXlZnEilC4FX+kgws2AoYA1fheRDbPjSFwn25W5pibUBAVSGgUOxYMPh4XYeNeQC6w25fWrQN7moP2xksn+eauRiZTUQ7fFbgCDYzIIV4y1EmtnzOGmsD8EP7EpVWr6W8EBOYbsMuusRhn0SyPFVMhqZ0tx39NyDs93/82MHGbgZxGf8jyBscwG40dOuyUeW8L8BZGRFU/Cl3rlyf94HeEoaaEa2wkaouw== azureuser@ansible-control"
    vm_size: Standard_B1ms
    network_interfaces: "{{ src_was_nic_name }}"
    image:
      offer: CentOS
      publisher: OpenLogic
      sku: '7.5'
      version: latest
    tags:
      level: dev
      application: was
      image: srcimg
